services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
